<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ES6_Promise的链式调用</title>
</head>
<body>
  <div>
    <p>ES6_Promise的链式调用</p>
  </div>
  <script>
    new Promise((resolve,reject)=>{
      setTimeout(()=>{
        resolve('Hello resolve')
        // reject('ERROR REJECT')

      },1000)
    }).then(res=>{
      // 1.第一次处理10行代码
      console.log(res,'第一层处理10行代码');
      // 2.对结果进行第一次处理
      // 写法一:
      // return new Promise((resolve)=>{
      //   resolve(res+'111')
      // })
      // 写法二:
      // return Promise.reject('error message')
      // return Promise.resolve('flag resolve')
      return 'flag resolve'
      //03-ES6_Promise的链式调用.html:21 Hello resolve 第一层处理10行代码
      // 03-ES6_Promise的链式调用.html:39 error message
      // 因为return返回了promise.reject
    }).then(res=>{
      // 3.第二次处理10行代码
      console.log(res,'第二层处理10行代码');
      // 4.对结果进行第二次处理
      return new Promise((resolve)=>{
        resolve(res+'222')
      })
    }).then(res=>{
      console.log(res,'第三层处理10行代码');
    }).catch(err=>{
      console.log(err);
    })
  </script>
  <!-- 
    1.打开resolve,注释掉reject
    浏览器返回:
    aaa 第一层处理10行代码 03-ES6_Promise的链式调用.html:19 
    aaa111 第二层处理10行代码 03-ES6_Promise的链式调用.html:26 
    aaa111222 第三层处理10行代码 03-ES6_Promise的链式调用.html:32 
    2.打开reject,注释掉resolve
    浏览器返回:ERROR REJECT 03-ES6_Promise的链式调用.html:36 

   -->
</body>
</html>








